version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: weekly
    day: sunday
    time: '00:00'
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
    - dassochu-150th
  assignees:
    - dassochu-150th
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: weekly
    day: sunday
    time: '00:00'
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
    - dassochu-150th
  assignees:
    - dassochu-150th
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
